gcc/5.4.0: add missing <signal.h> inclusion to asan
Without this patch glibc-2.25-r8 (ppc and ppc64) gcc build fails as:
  .../portage/sys-devel/gcc-5.4.0-r3/work/gcc-5.4.0/libsanitizer/asan/asan_linux.cc: In function 'bool __asan::AsanInterceptsSignal(int)':
  .../portage/sys-devel/gcc-5.4.0-r3/work/gcc-5.4.0/libsanitizer/asan/asan_linux.cc:222:20: error: 'SIGSEGV' was not declared in this scope
     return signum == SIGSEGV && common_flags()->handle_segv;
                      ^

Reported-by: Andreas K. Hüttel
Bug: https://bugs.gentoo.org/629502#c9